configs:
  cm:
    admin.enabled: false
    accounts.yumi: "login,apiKey"
    resource.customizations: |
      networking.k8s.io/Ingress:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
    resource.exclusions: |
      - apiGroups:
          - cilium.io
        kinds:
          - CiliumIdentity
        clusters:
          - "*"
  params:
    server.insecure: true
  rbac:
    policy.csv: |
      g, yumi, role:admin
    policy.default: role:readonly
