replicaCount: 1

image:
  repository: ghcr.io/robherley/snips.sh
  pullPolicy: IfNotPresent
  tag: "v0.2.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

services:
  http:
    type: ClusterIP
    port: 8080
  ssh:
    type: ClusterIP
    port: 2222

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
