on:
  pull_request:
    types: [review_requested, ready_for_review]
  push:
    branches:
      - master
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"

jobs:
  linux-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
        with:
          github_access_token: ${{ secrets.token }}
      - run: nix flake check --show-trace
  # NOTE: Technically it works, but, unlike nix flake check, it takes a century to complete, so I don't think it's worth using.
  #       Let it just be here in case someone will run into that.
  # macos-check:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: cachix/install-nix-action@v21
  #       with:
  #         github_access_token: ${{ secrets.token }}
  #         nix_path: "nixpkgs=channel:nixpkgs-23.05-darwin"
  #     - run: nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
  #     - run: nix-channel --add http://nixos.org/channels/nixpkgs-23.05-darwin nixpkgs && nix-channel --update
  #     - run: ./result/bin/darwin-installer
  #     - run: cat /etc/static/bashrc | grep environment | awk '{print $2}' | xargs cat
  #     - run: source /etc/static/bashrc && darwin-rebuild check --flake .#millia
