on:
  push:
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/main.yml"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.token }}
      - run: nix flake check --show-trace
